name: Release

on: 
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to platformio.ini'
        default: 'firmware/V1.2/Marlin-2.0.7.2-SKR-mini-E3-V1.2/platformio.ini'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DEBUG
        run: |
          ls
          ls firmware
          ls firmware/V1.2/Marlin-2.0.7.2-SKR-mini-E3-V1.2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run -t ${{ github.event.inputs.path }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          repo: ${{ github.event.inputs.path }}/.pio/build
